name: Create release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm i

      - name: Build project
        run: npm run build

      - name: Zip output folder
        run: cd dist && zip -r html-transformer.zip *

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/html-transformer.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}